spring:
  application:
    name: redis-session-management
  # Database configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/rbac_demo
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379
  session:
    redis:
      namespace: spring:session
      flush-mode: on_save

server:
  servlet:
    session:
      timeout: 30m

#JWT Token Configuration
jwt:
  secret: 80TMFC04qj9DeTh5S9KNEe3v0mAsO+o101pxwSD5oYQ0Dc5RXSJuna1XctOohWFPrDjQJst1wcCAa1pEhomNQ3S3qbSDg17BUvngtM10DfSdO9Fui64+fZwk9Zqmf18vJyZvnEVKsYJ30NIDTNoIFJcZVHHETxZr8AnxUJFmvPHlz9caewpjb+TcjgcOZLU8/SLgP+DP74uMm363DozooJXG7PIiAKAx1ixow2xpdBmT12qgatqxJkswo6AO4GGTK9xDQkCksrCGedHxI/NcjL+MT/EspjqUcIDopVdN/piWNgm71AAJ80DCzrQYYAQrah3jE8YbzPQ4R7ku+LWBTQ==
  issuer: learnwithiftekhar.com
  expiration: 3600000 # 1 hour in milliseconds
  refreshExpiration: 604800000 # 7 days in milliseconds
