spring.application.name=redis-session-management

# Database configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/rbac_demo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

#JWT Token Configuration
jwt.secret=80TMFC04qj9DeTh5S9KNEe3v0mAsO+o101pxwSD5oYQ0Dc5RXSJuna1XctOohWFPrDjQJst1wcCAa1pEhomNQ3S3qbSDg17BUvngtM10DfSdO9Fui64+fZwk9Zqmf18vJyZvnEVKsYJ30NIDTNoIFJcZVHHETxZr8AnxUJFmvPHlz9caewpjb+TcjgcOZLU8/SLgP+DP74uMm363DozooJXG7PIiAKAx1ixow2xpdBmT12qgatqxJkswo6AO4GGTK9xDQkCksrCGedHxI/NcjL+MT/EspjqUcIDopVdN/piWNgm71AAJ80DCzrQYYAQrah3jE8YbzPQ4R7ku+LWBTQ==
jwt.expiration=86400000
jwt.refreshExpiration=604800000
